name: check-pull-request

on:
  pull_request:
    branches: [ "main" ]
jobs:
  envi:
    runs-on: ubuntu-latest
    env: 
      CEP: ${{ env.CEP }}
      DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
      DATABASE_SCHEMA: ${{ env.DATABASE_SCHEMA }}
      DATABASE_URL: ${{ env.DATABASE_URL }}
      DATABASE_USERNAME: ${{ env.DATABASE_USERNAME }}
      SUPER_FRETE_URL: ${{ env.SUPER_FRETE_URL }}
      token: ${{ env.TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: maven
          cache-dependency-path: pom.xml
      - name: dev
        run:  mvn clean package