# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: ''
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        cache: maven
        cache-dependency-path: pom.xml
    - name: dev
      run:  mvn clean package -Dmaven.test.skip=true

  build-prod:
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: ''
    needs: build-dev
    steps:
    - uses: actions/checkout@v4
      with:
        java-version: '21'
        cache: maven
    - name: prod
      run: mvn --batch-mode  verify
